### ISSUE TITLE
구독 채널 순서 변경 테스트 케이스 오류

### ISSUE THREAD

**Issue by HJ-Rich** [woowacourse-teams/2022-pickpick#132]
# 버그 리포트

## 어떤 버그인가요?

> 버그에 대해 알려주세요

ChannelSubscriptionAcceptanceTest#구독_채널_순서_변경
위 테스트 케이스가 실패하고 있어요

<br><br>

## 어떤 상황에서 겪으셨나요?

> 버그를 겪으신 상황을 알려주세요

전체 테스트 케이스 실행 시 실패합니다.
ChannelOrderRequest 내 기본 생성자가 없어서 발생하는 이슈로 예상됩니다.
기본 생성자 추가 후 테스트 성공 확인했습니다.

<br><br>

## 참고할만한 자료가 있을까요?

> 참고자료가 있다면 첨부해주세요

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/62681566/179887992-d2f5d79d-1077-47af-8c7f-d3cad9c67556.png">

<br><br>

**Comment by JangBomi** [comment]
제 PC에서는 잘 돌아갔었는데, PC마다 다른가봐요.

https://github.com/woowacourse-teams/2022-pickpick/pull/129 pr에 ChannelOrderRequest 기본 생성자 추가하여 함께 올리겠습니다~ :)
