### ISSUE TITLE
무한 스크롤 관련 버그

### ISSUE THREAD

**Issue by kkojae91** [woowacourse-teams/2022-pickpick#147]
# 버그 리포트

## 어떤 버그인가요?

1. data cache가 되어 있는 경우, 날짜 드랍다운이 정상적으로 렌더링 되지 않는다.
2. data cache가 되어 있고, 스크롤이 하단에 있을 경우, cache되어 있는 날짜를 클릭할 때 스크롤이 이동하지 않는다.
3. data cache가 되어 있을 때, cache되어 있는 날짜로 query를 중복해서 날리게 되면 needPastMessages가 false로 요청되는 문제

<br><br>

## 참고할만한 자료가 있을까요?

뎃글로 남길 예정

<br><br>

**Comment by moonheekim0118** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/61469664/180132722-62655fe7-ea7c-4af6-af05-7de0f43c6aa1.gif)

**Comment by moonheekim0118** [comment]
#### data cache가 되어 있을 때, cache되어 있는 날짜로 query를 중복해서 날리게 되면 needPastMessages가 false로 요청되는 문제

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/61469664/180132829-3719cbda-ac61-4158-aaaf-58ac5786dd70.gif)

**Comment by moonheekim0118** [comment]
#### data cache가 되어 있고, 스크롤이 하단에 있을 경우, cache되어 있는 날짜를 클릭할 때 스크롤이 이동하지 않는다.
![](https://i.ibb.co/nMRWWCf/ezgif-com-gif-maker-2.gif)

**Comment by moonheekim0118** [comment]
data cache가 되어 있고, 스크롤이 하단에 있을 경우, cache되어 있는 날짜를 클릭할 때 스크롤이 이동하지 않는다.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/61469664/180133557-90903a43-247b-49f9-b59d-28129f4e2cc2.gif)
