### ISSUE TITLE
스크롤 위치가 0인 경우 이전 데이터 요청시 스크롤이 최상단으로 이동하는 버그

### ISSUE THREAD

**Issue by kkojae91** [woowacourse-teams/2022-pickpick#150]
# 버그 리포트

## 어떤 버그인가요?

스크롤 위치가 0인 경우 이전 데이터 요청시 스크롤이 최상단으로 이동하는 버그

<br><br>

## 참고할만한 자료가 있을까요?

뎃글로 남겨둘 예정입니다.

<br><br>

**Comment by moonheekim0118** [comment]
기능상 어쩔 수 없는 부분인데, 이걸 버그라고 표현하기가 애매하네요!
오히려 '기능 추가'라고 하는게 맞는 것 같은데, 실제 구현 가능한지는 더 알아봐야 할 것 같습니다 :)

**Comment by HJ-Rich** [comment]
이거 혹시 날짜로 이동할때만 위 아래로 요청을 두번보내서 양쪽을 다 렌더링해버리면 어떨까요?

Slack이 실제 그렇게 구현되어있길래 한 번 의견 투척해봅니다~!
