### ISSUE TITLE
구독한 채널 순서 변경 시 예외 케이스 추가 필요

### ISSUE THREAD

**Issue by yeon-06** [woowacourse-teams/2022-pickpick#159]
# 버그 리포트

## 어떤 버그인가요?

> 버그에 대해 알려주세요

구독한 채널에 대한 추가적인 예외 케이스 추가 구현 필요

<br><br>

## 어떤 상황에서 겪으셨나요?

> 버그를 겪으신 상황을 알려주세요

1. orderView에 -1, 0 등의 예상치 못한 숫자 입력

2. 한 사람이 구독한 채널에서 중복된 orderView 존재
    - A채널 orderView: 1
    - B채널 orderView: 2
    - C채널 orderView: 2

3. 구독 순서를 변경 시 해당 멤버가 구독한 적 없는 채널 ID 입력

4. 구독 순서를 변경 시 해당 멤버의 모든 구독채널이 request로 들어오지 않은 경우

5. 지난 PR 에서 TC refactoring 한거 빠진 부분 채워넣기

 <br><br>
## 참고할만한 자료가 있을까요?

> 참고자료가 있다면 첨부해주세요

https://github.com/woowacourse-teams/2022-pickpick/pull/152#discussion_r927222853

<br><br>

**Comment by JangBomi** [comment]
1번 상황 -> dto에 min(1) 추가 vs ChannelSubscription 엔티티 내부에 검증 로직 추가 논의해보기
