### ISSUE TITLE
Slack에 Github 연동

### ISSUE THREAD

**Issue by JangBomi** [woowacourse-teams/2022-pickpick#16]
## 목적  
Slack에 Github을 연동

## 상세 내용  
Slack에 Github를 연동하여, PR이나 ISSUE 등록 시 슬랙에서 알람을 받을 수 있도록 기능 추가

## 참고 사항  
https://github.com/integrations/slack#configuration

**Comment by HJ-Rich** [comment]
장보미 최고다~ 👍
