### ISSUE TITLE
Github 브랜치 프로텍션 룰, 머지 프로텍션 룰 설정

### ISSUE THREAD

**Issue by HJ-Rich** [woowacourse-teams/2022-pickpick#168]
# 신규 기능 개발

<br>

## 목적

> 이번 기능 개발의 목적을 간단히 적어주세요

- Github에서 제공하는 기능을 사용해보며 학습한다
- 모두가 Collaborator 로 설정되어 있어서 실수로 주요 브랜치에 바로 push 또는 delete를 할 수 있는 여지가 있다
  - 프로텍션 룰을 적용함으로써 이와 같은 상황을 미연에 방지할 수 있다
- PR의 경우에도, 특정 태그가 있을 경우, 특정인의 리뷰가 있을 때에만 머지 가능하다는 방어 옵션을 활성화 할 수 있다.

<br><br>

## 참고 사항

> 참고할 내용이 있다면 공유해주세요

![image](https://user-images.githubusercontent.com/62681566/180733637-a7303226-7de8-4d4f-99df-d66943ebb22f.png)

https://github.com/woowacourse-teams/2022-pickpick/settings/branch_protection_rules/new?branch_name=main
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

<br><br>

**Comment by yeon-06** [comment]
2022/08/04 리차드가 슬랙에 공유한 글

https://github.com/woowacourse-teams/2022-pickpick/wiki/Branch-Protection-Rule-%EC%A0%81%EC%9A%A9
- main과 release* 브랜치에 브랜치 프로텍션 룰 적용했습니다
- main과 release* 브랜치에 대해서 Github 내 파일 수정을 통한 의도치 않은 수정이 보호됩니다
- main과 release* 브랜치에 대해 로컬 개발환경에서 즉시 push가 불가해졌습니다
- main과 release* 브랜치에 변경이 필요할 경우 PR -> merge 과정을 거쳐야만 합니다
- Check가 통과해야 한다, 최소 n명의 Approval 을 받아야 한다 등의 옵션은 설정하지 않았습니다. 즉, 유사시 나홀로 PR -> merge도 가능합니다
- develop 브랜치에 대해서는 해당 룰을 적용하지 않았습니다. 실수로 변경해도 운영환경에 영향이 없고 개발편의성을 가져가는게 낫다고 판단했는데 필요시 적용 가능합니다
