### ISSUE TITLE
MemberIntializer에서 MethodsClient 직접 생성하는 코드 개선

### ISSUE THREAD

**Issue by yeon-06** [woowacourse-teams/2022-pickpick#214]
# 신규 기능 개발

<br>

## 목적

> 이번 기능 개발의 목적을 간단히 적어주세요

현재 MemberIntializer에서 MethodsClient 직접 생성하여 코드 개선 필요

<br><br>

## 상세 내용

> 구현할 기능 관련 상세 내용을 적어주세요

현재 MemberIntializer에서 MethodsClient 직접 생성중.
생성자를 통해 MethodsClient를 주입받도록 수정 필요

<br><br>

**Comment by JangBomi** [comment]
이거 리차드&봄 페어에서 개선했어요.! @Bean 이용해서 주입받게 수정했습니다 =:)
