### ISSUE TITLE
프론트엔드 CI/CD 환경 구축 

### ISSUE THREAD

**Issue by moonheekim0118** [woowacourse-teams/2022-pickpick#237]
## 목적

프론트엔드 CI/CD 환경 구축하여 빌드 배포 자동화를 한다. 🤞🏻

<br><br>

## 상세 내용

아마도 젠킨스..?

<br><br>

**Comment by HJ-Rich** [comment]
저희 [위키](https://github.com/woowacourse-teams/2022-pickpick/wiki/Github-Action%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-CI-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%9E%90%EB%8F%99%ED%99%94)에 정리해두었던 내용인데요,
아마 참고가 될 것 같습니다.

<br>

### [2021 GPU 내껀데](https://github.com/woowacourse-teams/2021-gpu-is-mine/tree/develop/.github/workflows)

- 하나의 yml 파일에 모든 내용을 담음
- FE-build, FE-test, FE-storybook-build, BE-build, BE-checkstyle, BE-test 등의 작업을 수행함

### [2021 여기서 만나](https://github.com/woowacourse-teams/2021-see-you-there/tree/develop/.github/workflows)

- 프론트엔드만 Github Action 사용
- npm install, npm run test 정도만 사용했음. 특정 브랜치 push 이벤트를 받아 처리하려 했음.
- 정규식을 이용했다는 점, 아주 심플하다는 점에서 참고될만할 듯

**Comment by moonheekim0118** [comment]
@kkojae91  @hyewoncc  @JangBomi  @yeon-06  수고하셨습니다
