### ISSUE TITLE
DatabaseCleaner 구현

### ISSUE THREAD

**Issue by HJ-Rich** [woowacourse-teams/2022-pickpick#254]
# 신규 기능 개발

<br>

## 목적

> 이번 기능 개발의 목적을 간단히 적어주세요

프로그래밍적 테스트 격리

<br><br>

## 상세 내용

> 구현할 기능 관련 상세 내용을 적어주세요

EntityManager를 이용해 전체 테이블명을 스캔한 뒤,
각 테이블을 순회하며 truncate를 실행하고, PK를 1로 되돌리는 작업을 구현합니다.
동적으로 진행되기 때문에 향후 테이블 추가 등이 일어나도 추가대응 없이 적용가능합니다.
부모 AcceptanceTest의 BeforeEach에서 선언해두면 
자식 클래스에서 매 테스트 메서드 실행 전 truncate가 됩니다.

단 테스트 종료 AcceptanceTest -> ServiceTest 등으로 진행될 때
종료된 이후 남는 데이터에 대해 어떻게 대응할지는 탐색이 조금 더 필요한 상황입니다.

<br><br>

## 참고 사항

> 참고할 내용이 있다면 공유해주세요

https://github.com/woowacourse-teams/2021-pick-git/blob/develop/backend/pick-git/src/test/java/com/woowacourse/pickgit/config/DatabaseConfigurator.java

<br><br>

**Comment by yeon-06** [comment]
깃들다의 경우에는 해당 부분을 개발하신 `손너잘`의 블로그를 보는게 이해가 쉬울 것 같아서 링크 첨부해둡니다
(총 5개의 글이 있네요)
1. [조회 관련은 DB를 분리한 이유 (간략한 버전)](https://bperhaps.tistory.com/entry/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-%EC%B5%9C%EC%A0%81%ED%99%94-%EC%97%AC%ED%96%89%EA%B8%B0-1)
2. [DirtiesContext 제거와 DB 클리너를 통해 DB 초기화](https://bperhaps.tistory.com/entry/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-%EC%B5%9C%EC%A0%81%ED%99%94-%EC%97%AC%ED%96%89%EA%B8%B0-2)
3. [@SpringBootTest와 @WebMvcTest는 다르다](https://bperhaps.tistory.com/entry/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-%EC%B5%9C%EC%A0%81%ED%99%94-%EC%97%AC%ED%96%89%EA%B8%B0-3)
4. [조회 관련은 DB를 분리한 이유 2 (디테일한 버전)](https://bperhaps.tistory.com/entry/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-%EC%B5%9C%EC%A0%81%ED%99%94-%EC%97%AC%ED%96%89%EA%B8%B0-4)
5. [조회 관련은 DB를 분리한 이유 3 (구현편)](https://bperhaps.tistory.com/entry/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-%EC%B5%9C%EC%A0%81%ED%99%94-%EC%97%AC%ED%96%89%EA%B8%B0-5)
