### ISSUE TITLE
메시지 목록 조회 API 페이징 default value를 정한다

### ISSUE THREAD

**Issue by HJ-Rich** [woowacourse-teams/2022-pickpick#27]
## 목적  

GET /api/messages?page={page}&size={size}
페이징 처리가 필요한 엔드포인트의 기본값을 정의해보면 어떨까요?~! 😄 

<br>

## 상세 내용  

백엔드쪽에선 default value 를 설정해주지 않으면,
QueryString이 전달되지 않았을 경우 예외가 발생하게 됩니다.
그래서 QueryString이 전달되지 않았을 경우에는 기본값으로 10개씩 나눈 1페이지를 반환한다
라는 식으로 합의를 해보면 어떨까 하는 생각입니다 ^^

<br>

## 참고 사항  

https://github.com/woowacourse-teams/2022-pickpick/wiki/%5B1%EC%B0%A8-%EC%8A%A4%ED%94%84%EB%A6%B0%ED%8A%B8%5D-%EB%A9%94%EC%8B%9C%EC%A7%80-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C-API-%EB%AA%85%EC%84%B8

**Comment by yeon-06** [comment]
default value 20으로 협의
