### ISSUE TITLE
ChanneId가 undefined 로 넘어가는 버그

### ISSUE THREAD

**Issue by moonheekim0118** [woowacourse-teams/2022-pickpick#314]
# 버그 리포트

## 어떤 버그인가요?

아주 가끔.. channelId undefined 로 넘어간다고 한다.

<br><br>

## 어떤 상황에서 겪으셨나요?

> 버그를 겪으신 상황을 알려주세요

<br><br>

## 참고할만한 자료가 있을까요?

> 참고자료가 있다면 첨부해주세요

<br><br>

**Comment by HJ-Rich** [comment]
@moonheekim0118 @kkojae91 
백엔드에서도 `channelIds=undefined` 로 전달될 경우에 대해 해당 내용은 무시하도록 대응하겠습니다.
