### ISSUE TITLE
Slack 이벤트 명에 대응되는 서비스 클래스 네이밍 개선

### ISSUE THREAD

**Issue by HJ-Rich** [woowacourse-teams/2022-pickpick#38]
## 목적  

- 추후 개발 시 착오를 줄이기 위한 이벤트별 핸들링 클래스 네이밍 개선

<br>

## 상세 내용  

- `MESSAGE_CREATED` 와 같은 Enum 명칭을 Slack 이벤트 타입을 그대로 차용해 사용하고 있는데,
이 이벤트를 처리하는 구현체의 이름은 현재 `MessageSaveService` 임.
- 가능하다면 MessageCreatedService 와 같은 네이밍을 채택하여 향후 일관성을 유지하면 어떨지 제안.

<br>

## 참고 사항  

- [Slack Event API Types](https://api.slack.com/events)

<br>

**Comment by yeon-06** [comment]
#42 에서 개선된 사항이므로 해당 이슈 closed 처리
