### ISSUE TITLE
이슈 템플릿 개행 추가

### ISSUE THREAD

**Issue by HJ-Rich** [woowacourse-teams/2022-pickpick#39]
## 목적  

- 가독성 개선을 위한 이슈 템플릿 내 개행 추가

## 상세 내용  

```
---

name: Default issue
about: Suggest an idea for this project
title: "명사형으로 작성"
labels: ''
assignees: ''

---  

## 목적  


<br>

## 상세 내용  


<br>

## 참고 사항  


<br>

```

<br>

## 참고 사항  
https://github.com/woowacourse-teams/2022-pickpick/blob/main/.github/ISSUE_TEMPLATE/DEFAULT_TEMPLATE.md

<br>

**Comment by yeon-06** [comment]
이 이슈는 나중에 #6 이랑 같이 수정되면 좋을 것 같네요👍
