### ISSUE TITLE
Database 이관

### ISSUE THREAD

**Issue by yeon-06** [woowacourse-teams/2022-pickpick#445]
# 신규 기능 개발

<br>

## 목적

> 이번 기능 개발의 목적을 간단히 적어주세요

Database 이관

<br><br>

## 상세 내용

> 구현할 기능 관련 상세 내용을 적어주세요

기존에 리차드의 개인 AWS에 생성된 RDS 대신 우테코의 AWS에 새로 생성 후 이관

<br><br>

**Comment by JangBomi** [comment]
이관하면서 기존 DB에 있던 데이터 옮겨주세용,,,
