### ISSUE TITLE
ErrorResponse 반환 객체가 없음

### ISSUE THREAD

**Issue by JangBomi** [woowacourse-teams/2022-pickpick#450]
# 신규 기능 개발

<br>

## 목적

> 이번 기능 개발의 목적을 간단히 적어주세요

ErrorResponse 반환 객체가 없음

<br><br>

## 상세 내용

> 구현할 기능 관련 상세 내용을 적어주세요

ErrorResponse를 반환하는 객체가 없이 서버에서 로그만 찍고 있어서
프론트에서의 에러 핸들링이 의미가 없어요 ;-;

<br><br>

## 참고 사항

> 참고할 내용이 있다면 공유해주세요

<img width="876" alt="image" src="https://user-images.githubusercontent.com/55357130/185071176-bfc3130b-f68c-47dd-8085-ed4aa4022c8a.png">

<br><br>

**Comment by HJ-Rich** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 왜케 웃기징... 😿
