### ISSUE TITLE
MessageServiceTest에 DatabaseCleaner 적용

### ISSUE THREAD

**Issue by JangBomi** [woowacourse-teams/2022-pickpick#501]
# 신규 기능 개발

<br>

## 목적

> 이번 기능 개발의 목적을 간단히 적어주세요

MessageServiceTest에 DatabaseCleaner 적용

<br><br>

## 상세 내용

> 구현할 기능 관련 상세 내용을 적어주세요

9월 14일 기준으로는 MessageServiceTest에 DatabaseCleaner가 적용되어있습니다.
하지만 써머의 MessageServiceTest 대대적인 리팩토링에 대한 pr이 머지될 때 아마도 충돌이 발생할꺼고, 그 때 써머의 MessageServiceTest 파일 기준으로 머지를 진행하고, 이후에 MessageServiceTest에 다시 DatabaseCleaner를 적용합니다!

<br><br>

## 참고 사항

> 참고할 내용이 있다면 공유해주세요

[DB cleaner PR의 써머&봄 댓글](https://github.com/woowacourse-teams/2022-pickpick/pull/479#discussion_r970406367)

<br><br>

**Comment by hyewoncc** [comment]
#421 
해당 PR 머지하며 적용해서 이슈 닫겠습니다 👏
