### ISSUE TITLE
운영 배포 시 DB bookmark 테이블 업데이트 

### ISSUE THREAD

**Issue by hyewoncc** [woowacourse-teams/2022-pickpick#586]
# 신규 기능 개발

## 목적

운영 배포 시 DB bookmark 테이블을 업데이트한다  

## 상세 내용

bookmark 테이블에 변경이 있었습니다  
생성시각을 담는 `created_date` 컬럼이 `timestamp(6)`으로 추가되어야 합니다  
❗️개발DB는 적용되어 있습니다  

<br>

**Comment by JangBomi** [comment]
## 완료

<img width="559" alt="image" src="https://user-images.githubusercontent.com/55357130/197095335-688f935d-7f6e-46bd-a955-12c1e2457f2d.png">
