### ISSUE TITLE
이용 방법 문구 변경

### ISSUE THREAD

**Issue by yeon-06** [woowacourse-teams/2022-pickpick#666]
# 신규 기능 개발

<br>

## 목적

> 이번 기능 개발의 목적을 간단히 적어주세요

이용 방법 문구 변경

<br><br>

## 상세 내용

> 구현할 기능 관련 상세 내용을 적어주세요

현재 줍줍 사이트에 방문하면 아래와 같은 문구가 뜹니다
해당 문구를 현재의 서비스에 맞게 변경하면 좋을 것 같습니다
새로 변경될 문구는 팀 모두가 함께 의논해봅시다😄

![image](https://user-images.githubusercontent.com/53105735/197322156-6bb6c55d-018c-4cbf-99c9-88f25715ac5e.png)

<br><br>

**Comment by moonheekim0118** [comment]
1. 워크스페이스 등록 클릭 (줍줍 슬랙 앱이 해당 워크스페이스에 설치된다.)
2. 로그인을 한다. 
3. 채널을 구독 봇을 채널에 추가한다.

**Comment by moonheekim0118** [comment]
1. 워크스페이스 등록을 클릭하면 줍줍 슬랙 앱이 해당 워크스페이스에 설치 됩니다.
2. 이제 줍줍이 설치 된 채널의 메시지가 백업 됩니다.
3. 메시지를 확인하시려면, 로그인 후 채널을 구독해주세요.
 
- 아래에 docs how to use (자세하게)
