### ISSUE TITLE
SlackEvent 관련 클래스 네이밍 변경 제안

### ISSUE THREAD

**Issue by yeon-06** [woowacourse-teams/2022-pickpick#700]
## 목적

> 이번 기능 개발의 목적을 간단히 적어주세요

SlackEvent 관련 클래스 네이밍 변경 제안

<br><br>

## 상세 내용

> 구현할 기능 관련 상세 내용을 적어주세요

- Service -> Handler
  - SlackEventServiceFinder -> SlackEventHandlerManager
  - MessageCreatedService -> MessageCreatedHandler ... 

이름 변경 제안 사유
- Service라는 이름이 일반적으로 사용되는 경우와는 달라 설명 시 많은 사람들이 헷갈려한다는 느낌을 받았습니다. 좀 더 명확한 이름을 갖게 만들고자 제안 드립니다

<br><br>

**Comment by JangBomi** [comment]
이슈에 대한 댓글이 늦었네요 ㅠㅠ 저는 이름 변경 너무 좋은 것 같아요. 확실히 좀 헷갈리는 것 같기도 하고요.

관련해서 내용 써치하다가 [이글](https://mangkyu.tistory.com/252) 발견했는데 저희 현재 구조랑 동일한 것 같네요!!
저 글 하단에 캐싱에 대한 이야기도 있어서 한 번 보시면 좋을 것 같아요! :)

이름에 대한 변경은 저는 매우매우 찬성합니닷 👍
