### ISSUE TITLE
Slack 메시지 저장 누락 케이스 및 저장되지 않아야 할 케이스 대응

### ISSUE THREAD

**Issue by yeon-06** [woowacourse-teams/2022-pickpick#98]
# 신규 기능 개발

<br>

## 목적

> 이번 기능 개발의 목적을 간단히 적어주세요

슬랙 메시지 저장 요청에서의 예외 케이스 처리

<br><br>

## 상세 내용

> 구현할 기능 관련 상세 내용을 적어주세요

`사용자가 채널에 참여함` 등의 불필요한 메시지는 DB에 저장되지 않도록 예외 처리를 한다.

<br><br>

**Comment by HJ-Rich** [comment]
## 스레드 메시지도 저장되는 현상에 대해 확인한 내용에 대해 공유합니다.

---

### 현재 스레드 메시지가 저장되고 있는 이유

- Slack 측에서 스레드 메시지의 경우 type, subtype을 신규 메시지와 동일하게 보내고 있음 ("message", ❌)
- 따라서 개별 메시지처럼 저장되고 있는 게 맞음
- 이는 Slack 측에서 버그로 인지하고 있으며, 고칠 때까지 다른 수단을 이용해 스레드 메시지인지 구분하라고 함
- `message.thread_ts` 값이 존재하면 스레드 메시지라고 함

<br>

### 대응할 내용

- `message.thread_ts` 값이 있으면 요청을 무시해야함

<br>

### 참고자료

```
Bug alert! This event is missing the subtype field when dispatched over the Events API. 
Until it is fixed, examine message events' thread_ts value. When present, it's a reply.
To be doubly sure, compare a thread_ts to the top-level ts value, 
when they differ the latter is a reply to the former.
```

<img width="764" alt="image" src="https://user-images.githubusercontent.com/62681566/180156406-58c2051c-992b-4737-a7a1-0a623b27fe91.png">

https://api.slack.com/events/message/message_replied

<br>

**Comment by JangBomi** [comment]
[노션에 `message` 타입의 서브타입 및 각 서브타입의 필요성을 정리한 링크](https://www.notion.so/richard7/8ac56153a15e4171a1e91307f3412f5a#eb96a0e9b3cf45d9adf23d485d9458cc)

**Comment by HJ-Rich** [comment]
### 저장되어야 하는데 누락되고 있는 케이스

---

[me_message](https://api.slack.com/events/message/me_message)
[thread_broadcast](https://api.slack.com/events/message/thread_broadcast)
[file_share](https://api.slack.com/events/message/file_share)

<br><br>

### 저장 되고 있는 데 제외해야 하는 케이스

---

[message_replied](https://api.slack.com/events/message/message_replied)

**Comment by JangBomi** [comment]
#224  
파일 공유 메시지에 대해 분리하여 이슈를 생성했습니다

#225
해당 이슈는 위 PR에서 작업하였습니다

**Comment by JangBomi** [comment]
me_message는 적용하지 않도록 논의 완료

**Comment by JangBomi** [comment]
file_share 메시지 재적용 필요

**Comment by JangBomi** [comment]
모든 케이스 처리되어 이슈 닫습니다 🚪
