### ISSUE TITLE
양방향 무한 스크롤 로직 리팩토링

### ISSUE THREAD

**Issue by moonheekim0118** [woowacourse-teams/2022-pickpick#99]
## 목적

양방향 무한 스크롤 로직을 리팩토링한다. 💪

<br><br>

## 상세 내용

- 중복되는 로직을 Hook 으로 분리한다. 
- 매직 넘버를 제거한다. 
- 네이밍을 통일한다.

**Comment by HJ-Rich** [comment]
백엔드도 얼마전 관련 로직을 리팩터링 했었어요~! ㅋ.ㅋ
멋집니다!!
최강 프론트 화이팅!! 💪
